### ISSUE TITLE
Generate JavaDoc and Sources of Jakarta Classifier?

### ISSUE THREAD

**Issue by melloware** [yupiik/maven-shade-transformers#11]
Sorry @rmannibucau didn't know where else to ask but we got this report:

https://github.com/primefaces-extensions/primefaces-extensions/issues/1254

Basically we are shading to a jakarta classifier but even with `<createSourcesJar>true</createSourcesJar>` its creating an empty JAR.  I would love to be able to generate sources and javadocs for this shaded classifier JAR.  Do you think its possible?

**Comment by rmannibucau** [comment]
@melloware where -> maven user list I guess, about your issue -> I'd ensure source (resp javadoc) jar is attached to the project *before* shade phase.

**Comment by melloware** [comment]
nailed it i moved my shade phase to verify. Thanks!
