### ISSUE TITLE
RelocationTransformer should use project.build.sourceEncoding as encoding

### ISSUE THREAD

**Issue by tandraschko** [yupiik/maven-shade-transformers#9]
and pass it to IOUtils + use it in getBytes: https://github.com/yupiik/maven-shade-transformers/blob/master/src/main/java/io/yupiik/maven/shade/transformer/RelocationTransformer.java#L65

also maybe allow to overwrite

**Comment by fpapon** [comment]
@tandraschko hi! Thank you for raising this issue, are you planning to provide a PR?

**Comment by melloware** [comment]
I can take a crack at it.

**Comment by melloware** [comment]
@fpapon Confirmed 0.0.4 is in Central and has fixed our issues!

**Comment by fpapon** [comment]
> @fpapon Confirmed 0.0.4 is in Central and has fixed our issues!

Thank for using and contributing on it!
